import { DotSpec } from '../../types';

export const hardwareDotsTemplate: DotSpec[] = [
  {
    id: 'dot-hardware-eng',
    name: 'Hardware Systems DOT',
    icon: 'Cpu',
    role: 'PCB Design & Microcontroller Architecture',
    goal: 'Select MCU, battery power budget, sensor topology, bus protocols (I2C/SPI), and CAD enclosure specs.',
    tools: ['ComponentOctopart', 'KiCadGen', 'PowerBudgetCalculator'],
    dependsOn: [],
    outputs: ['schematic_overview', 'competitor_table', 'sources'],
    requiresApproval: true,
    status: 'idle',
    color: '#06b6d4',
    stage: 1,
  },
  {
    id: 'dot-supply-chain',
    name: 'Supply Chain & BOM DOT',
    icon: 'Truck',
    role: 'Bill of Materials & Contract Manufacturer Selection',
    goal: 'Generate component-level BOM, identify single-source risks, estimate lead times, and vet Shenzhen/US CMs.',
    tools: ['OctopartBOM', 'LeadTimeForecaster', 'FactoryMatcher'],
    dependsOn: [],
    outputs: ['bom_breakdown', 'supplier_risk_matrix'],
    requiresApproval: false,
    status: 'idle',
    color: '#3b82f6',
    stage: 1,
  },
  {
    id: 'dot-firmware',
    name: 'Firmware & Edge AI DOT',
    icon: 'Terminal',
    role: 'Embedded RTOS & On-Device Inference',
    goal: 'Architect low-latency sensor loop, TinyML quantization, OTA firmware updates, and Bluetooth Low Energy stack.',
    tools: ['FreeRTOSArchitect', 'EdgeImpulseOptimizer', 'BLEProfileGen'],
    dependsOn: ['dot-hardware-eng'],
    outputs: ['mvp_features', 'firmware_state_machine'],
    requiresApproval: true,
    status: 'idle',
    color: '#8b5cf6',
    stage: 2,
  },
  {
    id: 'dot-compliance',
    name: 'Regulatory & FCC DOT',
    icon: 'Award',
    role: 'FCC, CE, RoHS & Battery Safety Certification',
    goal: 'Map compliance testing requirements (FCC Part 15, UN38.3 lithium battery, CE radio equipment directive).',
    tools: ['TestLabDirectory', 'ComplianceChecklistGen', 'SafetyStandardDb'],
    dependsOn: ['dot-hardware-eng', 'dot-firmware'],
    outputs: ['tech_architecture', 'compliance_roadmap'],
    requiresApproval: false,
    status: 'idle',
    color: '#10b981',
    stage: 3,
  },
  {
    id: 'dot-hardware-econ',
    name: 'Hardware COGS & Capex DOT',
    icon: 'Coins',
    role: 'Tooling Molds, Landed COGS & Margin Matrix',
    goal: 'Calculate tooling injection mold costs ($25k-$80k), landed COGS, distributor vs DTC gross margins, and MOQ scale curve.',
    tools: ['ToolingAmortizationModel', 'COGSWaterfall', 'CashFlowBurnCalc'],
    dependsOn: ['dot-firmware', 'dot-supply-chain'],
    outputs: ['unit_economics'],
    requiresApproval: true,
    status: 'idle',
    color: '#f59e0b',
    stage: 4,
  },
  {
    id: 'dot-crowdfund',
    name: 'Pre-Order & D2C Launch DOT',
    icon: 'Sparkles',
    role: 'Kickstarter / Backer Campaign & Beta Units',
    goal: 'Build pre-order funnel, early backer reward tiers, manufacturing progress updates, and initial 1,000 unit batch plan.',
    tools: ['KickstarterBenchmark', 'BackerSequenceGen', 'PressKitBuilder'],
    dependsOn: ['dot-hardware-econ'],
    outputs: ['launch_plan'],
    requiresApproval: false,
    status: 'idle',
    color: '#ec4899',
    stage: 4,
  },
];
