import { DotSpec } from '../../types';

export const marketplaceDotsTemplate: DotSpec[] = [
  {
    id: 'dot-supply',
    name: 'Supply-Side Growth DOT',
    icon: 'Store',
    role: 'Merchant / Provider Acquisition & Onboarding',
    goal: 'Build cold supply-side acquisition playbooks, merchant incentives, and frictionless onboarding workflows.',
    tools: ['DirectoryScraper', 'ColdEmailOutreach', 'IncentiveCalculator'],
    dependsOn: [],
    outputs: ['supply_strategy', 'merchant_onboarding_flow'],
    requiresApproval: true,
    status: 'idle',
    color: '#06b6d4',
    stage: 1,
  },
  {
    id: 'dot-demand',
    name: 'Demand-Side Acquisition DOT',
    icon: 'Users',
    role: 'Buyer Growth & Search Intent Optimizer',
    goal: 'Model consumer search intent, programmatic SEO landing pages, and repeat purchase retention hooks.',
    tools: ['AhrefsScraper', 'AdCreativeGen', 'CohortRetentionModel'],
    dependsOn: [],
    outputs: ['demand_funnel', 'competitor_table', 'sources'],
    requiresApproval: false,
    status: 'idle',
    color: '#3b82f6',
    stage: 1,
  },
  {
    id: 'dot-liquidity',
    name: 'Liquidity & Matching DOT',
    icon: 'GitFork',
    role: 'Marketplace Density & Dynamic Matching',
    goal: 'Design two-sided matching logic, minimum supply thresholds per geo/category, and time-to-fulfillment curves.',
    tools: ['NetworkEffectSim', 'DispatchOptimizer', 'DensityMapper'],
    dependsOn: ['dot-supply', 'dot-demand'],
    outputs: ['mvp_features', 'matching_algorithm_spec'],
    requiresApproval: true,
    status: 'idle',
    color: '#8b5cf6',
    stage: 2,
  },
  {
    id: 'dot-trust',
    name: 'Trust & Escrow DOT',
    icon: 'ShieldCheck',
    role: 'Fraud Prevention, Ratings & Payment Disputes',
    goal: 'Specify escrow payment infrastructure, KYC verification steps, dispute arbitration, and review authenticity.',
    tools: ['StripeConnectArchitect', 'FraudRuleBuilder', 'IdentityVerifier'],
    dependsOn: ['dot-liquidity'],
    outputs: ['tech_architecture', 'dispute_matrix'],
    requiresApproval: false,
    status: 'idle',
    color: '#10b981',
    stage: 3,
  },
  {
    id: 'dot-economics',
    name: 'Take-Rate & GMV DOT',
    icon: 'CircleDollarSign',
    role: 'Two-Sided Rake & Unit Economics',
    goal: 'Model GMV, take-rate percentages (12-18%), payment processing friction, and dual-sided CAC recovery.',
    tools: ['TakeRateOptimizer', 'GMVForecaster', 'DualSideLTVModel'],
    dependsOn: ['dot-liquidity'],
    outputs: ['unit_economics'],
    requiresApproval: true,
    status: 'idle',
    color: '#f59e0b',
    stage: 4,
  },
  {
    id: 'dot-growth',
    name: 'Marketplace Launch DOT',
    icon: 'Flame',
    role: 'Constrained City/Vertical Launch Playbook',
    goal: 'Design high-density initial launch targeting single micro-market (e.g. single campus or city neighborhood).',
    tools: ['MicroMarketPlanner', 'CampusAmbassadorPlaybook', 'LaunchMilestones'],
    dependsOn: ['dot-liquidity'],
    outputs: ['launch_plan'],
    requiresApproval: false,
    status: 'idle',
    color: '#ec4899',
    stage: 4,
  },
];
