import { DotSpec } from '../../types';

export const saasDotsTemplate: DotSpec[] = [
  {
    id: 'dot-research',
    name: 'Market Intelligence DOT',
    icon: 'Radar',
    role: 'Competitive Landscape & Moat Strategist',
    goal: 'Analyze existing software competitors, market gaps, wedge strategies, and defensible positioning vectors.',
    tools: ['WebSearch', 'CrunchbaseAPI', 'SimilarWeb', 'SemanticDiff'],
    dependsOn: [],
    outputs: ['competitor_table', 'sources'],
    requiresApproval: true,
    status: 'idle',
    color: '#06b6d4',
    stage: 1,
  },
  {
    id: 'dot-user-research',
    name: 'Persona & ICP DOT',
    icon: 'Users',
    role: 'Ideal Customer Profile & Pain Synthesis',
    goal: 'Model target user workflows, jobs-to-be-done, friction points, and willingness-to-pay thresholds.',
    tools: ['RedditScraper', 'InterviewSynthesizer', 'G2ReviewMiner'],
    dependsOn: [],
    outputs: ['user_personas', 'jtbd_framework'],
    requiresApproval: false,
    status: 'idle',
    color: '#3b82f6',
    stage: 1,
  },
  {
    id: 'dot-product',
    name: 'Product Architect DOT',
    icon: 'Boxes',
    role: 'MVP Feature Scope & User Journey Spec',
    goal: 'Synthesize research into a tight, phased MVP feature spec with user journeys and zero bloat.',
    tools: ['SpecBuilder', 'UserStoryGenerator', 'MermaidDiagrammer'],
    dependsOn: ['dot-research', 'dot-user-research'],
    outputs: ['mvp_features', 'user_flows'],
    requiresApproval: true,
    status: 'idle',
    color: '#8b5cf6',
    stage: 2,
  },
  {
    id: 'dot-tech',
    name: 'Full-Stack Systems DOT',
    icon: 'Cpu',
    role: 'Modern Cloud & AI Systems Architecture',
    goal: 'Select battle-tested tech stack, design schema, choose LLM orchestration patterns, and estimate infra costs.',
    tools: ['ArchitecturePlanner', 'SchemaValidator', 'CostEstimator'],
    dependsOn: ['dot-product'],
    outputs: ['tech_architecture'],
    requiresApproval: false,
    status: 'idle',
    color: '#10b981',
    stage: 3,
  },
  {
    id: 'dot-finance',
    name: 'Unit Economics DOT',
    icon: 'TrendingUp',
    role: 'SaaS Pricing & Financial Modeling',
    goal: 'Calculate CAC, LTV, gross margin, payback periods, and 12-month MRR growth trajectory.',
    tools: ['FinancialModeler', 'MonteCarloSim', 'BenchmarkingEngine'],
    dependsOn: ['dot-product'],
    outputs: ['unit_economics'],
    requiresApproval: true,
    status: 'idle',
    color: '#f59e0b',
    stage: 4,
  },
  {
    id: 'dot-growth',
    name: 'GTM Launch DOT',
    icon: 'Rocket',
    role: 'Acquisition Funnel & Launch Sequencing',
    goal: 'Construct Day 1 to Day 90 go-to-market plan covering Product Hunt, developer communities, and viral loops.',
    tools: ['LaunchStrategist', 'CopywriterAgent', 'ViralKFactorModel'],
    dependsOn: ['dot-product'],
    outputs: ['launch_plan'],
    requiresApproval: false,
    status: 'idle',
    color: '#ec4899',
    stage: 4,
  },
];
