import { DotSpec } from '../../types';

export const serviceDotsTemplate: DotSpec[] = [
  {
    id: 'dot-workflow',
    name: 'Workflow Automation DOT',
    icon: 'Workflow',
    role: 'SOP to Autonomous Pipeline Architect',
    goal: 'Deconstruct manual human workflows into modular automated steps with human-in-the-loop validation.',
    tools: ['ProcessMapper', 'ZapierWebhookGen', 'SOPParser'],
    dependsOn: [],
    outputs: ['process_audit', 'competitor_table', 'sources'],
    requiresApproval: true,
    status: 'idle',
    color: '#06b6d4',
    stage: 1,
  },
  {
    id: 'dot-packaging',
    name: 'Productized Scope DOT',
    icon: 'Package',
    role: 'Fixed-Scope Offering & Tier Architecture',
    goal: 'Eliminate hourly billing by structuring 3 standardized productized tiers with clear SLAs and deliverables.',
    tools: ['ScopeMatrixGen', 'PricingCalculator', 'DeliverableContractDb'],
    dependsOn: [],
    outputs: ['mvp_features', 'tier_packaging'],
    requiresApproval: false,
    status: 'idle',
    color: '#3b82f6',
    stage: 1,
  },
  {
    id: 'dot-delivery',
    name: 'Autonomous Delivery DOT',
    icon: 'Activity',
    role: 'Client Onboarding & Real-time SLA Engine',
    goal: 'Automate client questionnaire intake, kick-off documentation, and asynchronous progress dashboards.',
    tools: ['NotionClientPortalGen', 'SlackAgentNotifier', 'QualityScorer'],
    dependsOn: ['dot-workflow', 'dot-packaging'],
    outputs: ['tech_architecture', 'client_portal_spec'],
    requiresApproval: true,
    status: 'idle',
    color: '#8b5cf6',
    stage: 2,
  },
  {
    id: 'dot-utilization',
    name: 'Gross Margin & Capacity DOT',
    icon: 'DollarSign',
    role: 'Client Retention & Gross Profit Per Account',
    goal: 'Model revenue per autonomous seat, compute gross margin (>85%), compute payback on client acquisition.',
    tools: ['GrossMarginForecaster', 'CapacityPlanner', 'ChurnRiskModel'],
    dependsOn: ['dot-delivery'],
    outputs: ['unit_economics'],
    requiresApproval: true,
    status: 'idle',
    color: '#f59e0b',
    stage: 3,
  },
  {
    id: 'dot-inbound',
    name: 'High-Ticket Inbound DOT',
    icon: 'Target',
    role: 'B2B Account Based Marketing & Case Studies',
    goal: 'Build cold outbound sequences targeting VP/C-suite decision makers with personalized teardown audits.',
    tools: ['ApolloScraper', 'ColdEmailSequence', 'CaseStudyBuilder'],
    dependsOn: ['dot-delivery'],
    outputs: ['launch_plan'],
    requiresApproval: false,
    status: 'idle',
    color: '#ec4899',
    stage: 4,
  },
];
