import React, { useState } from 'react';
import { useDotsStore } from '../../store/useDotsStore';
import { DotOutput } from '../../types';
import {
  ResponsiveContainer,
  AreaChart,
  Area,
  XAxis,
  YAxis,
  Tooltip,
  CartesianGrid,
  Legend,
} from 'recharts';
import {
  ExternalLink,
  Sparkles,
  Cpu,
  RefreshCw,
  FileText,
} from 'lucide-react';

export const OutputsView: React.FC = () => {
  const { outputs, dots, selectedDotId, setSelectedDotId } = useDotsStore();

  const outputList = Object.values(outputs);

  const [activeOutputId, setActiveOutputId] = useState<string>(
    selectedDotId && outputs[selectedDotId] ? selectedDotId : outputList[0]?.dotId || ''
  );

  const currentOutput: DotOutput | undefined =
    outputs[activeOutputId] || outputList[0];

  return (
    <div className="flex flex-col h-full bg-[#090b10] rounded-2xl border border-white/10 overflow-hidden">
      {/* Top Deliverables Tab Bar */}
      <div className="p-4 border-b border-white/10 bg-[#0d1017]/90 backdrop-blur-md flex flex-wrap items-center justify-between gap-3">
        <div>
          <h3 className="text-sm font-bold text-white flex items-center gap-2">
            <Sparkles className="w-4 h-4 text-slate-300" />
            <span>Autonomous Venture Deliverables ({outputList.length})</span>
          </h3>
          <p className="text-xs text-slate-400">
            High-fidelity specs, models, source-linked research, and system blueprints generated by DOTs.
          </p>
        </div>

        {/* Tab selector for available outputs */}
        <div className="flex items-center gap-1.5 overflow-x-auto max-w-full">
          {outputList.map((out) => {
            const isSelected = currentOutput?.dotId === out.dotId;
            const sourceDot = dots.find((d) => d.id === out.dotId);
            return (
              <button
                key={out.dotId}
                onClick={() => {
                  setActiveOutputId(out.dotId);
                  setSelectedDotId(out.dotId);
                }}
                className={`px-3 py-1.5 rounded-xl text-xs font-medium whitespace-nowrap transition-all cursor-pointer ${
                  isSelected
                    ? 'bg-white/15 text-white border border-white/20'
                    : 'bg-white/5 text-slate-400 border border-white/5 hover:text-white'
                }`}
              >
                {sourceDot?.name || out.title.split('—')[0]}
              </button>
            );
          })}
        </div>
      </div>

      {/* Main Content Area */}
      <div className="flex-1 overflow-y-auto p-6">
        {!currentOutput ? (
          <div className="h-64 flex flex-col items-center justify-center text-center">
            <FileText className="w-10 h-10 text-slate-600 mb-2" />
            <p className="text-sm text-slate-400 font-medium">No deliverables generated yet.</p>
            <p className="text-xs text-slate-500 mt-1 max-w-sm">
              Run the organization simulation from the Task Graph or individual DOTs to generate production artifacts.
            </p>
          </div>
        ) : (
          <div className="space-y-6 max-w-5xl mx-auto">
            {/* Header info card */}
            <div className="p-5 rounded-2xl glass-panel border border-white/10">
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 mb-2">
                <h2 className="text-lg font-bold text-white">{currentOutput.title}</h2>
                <span className="text-[11px] font-mono text-slate-400">
                  Generated at {currentOutput.timestamp}
                </span>
              </div>
              <p className="text-xs text-slate-300 leading-relaxed font-normal">
                {currentOutput.summary}
              </p>

              {/* Revision banner if revised based on feedback */}
              {currentOutput.isRevised && (
                <div className="mt-3 p-3 rounded-xl bg-amber-950/40 border border-amber-500/40 text-amber-200 text-xs flex items-start gap-2 shadow-sm">
                  <RefreshCw className="w-4 h-4 text-amber-400 shrink-0 mt-0.5" />
                  <div>
                    <span className="font-bold uppercase tracking-wider text-[10px] text-amber-400 block">
                      Revised on Founder Feedback
                    </span>
                    <span className="italic font-normal">"{currentOutput.revisionComment}"</span>
                  </div>
                </div>
              )}
            </div>

            {/* Competitor Table with Source Links */}
            {currentOutput.type === 'competitor_table' && currentOutput.data.competitors && (
              <div className="space-y-4">
                <div className="rounded-2xl border border-white/10 overflow-hidden bg-white/[0.01]">
                  <div className="overflow-x-auto">
                    <table className="w-full text-left text-xs">
                      <thead className="bg-[#121622] text-slate-400 uppercase text-[10px] font-mono border-b border-white/10">
                        <tr>
                          <th className="p-3.5">Incumbent</th>
                          <th className="p-3.5">Key Strengths</th>
                          <th className="p-3.5">Core Weaknesses</th>
                          <th className="p-3.5 text-white">DOTS Differentiation Moat</th>
                          <th className="p-3.5">Pricing Model</th>
                          <th className="p-3.5">Source Link</th>
                        </tr>
                      </thead>
                      <tbody className="divide-y divide-white/5 text-slate-300">
                        {currentOutput.data.competitors.map((comp, idx) => (
                          <tr key={idx} className="hover:bg-white/[0.02] transition-colors">
                            <td className="p-3.5 font-bold text-white whitespace-nowrap">
                              {comp.name}
                            </td>
                            <td className="p-3.5 max-w-[200px] leading-relaxed text-slate-300">
                              {comp.strengths}
                            </td>
                            <td className="p-3.5 max-w-[200px] leading-relaxed text-slate-400">
                              {comp.weaknesses}
                            </td>
                            <td className="p-3.5 max-w-[220px] leading-relaxed text-slate-200 font-medium">
                              {comp.differentiation}
                            </td>
                            <td className="p-3.5 font-mono text-[11px] whitespace-nowrap">
                              {comp.pricing}
                            </td>
                            <td className="p-3.5 whitespace-nowrap">
                              <a
                                href={comp.sourceUrl}
                                target="_blank"
                                rel="noreferrer"
                                className="inline-flex items-center gap-1 text-[11px] text-slate-300 hover:text-white underline font-mono"
                              >
                                <span>Verify</span>
                                <ExternalLink className="w-3 h-3" />
                              </a>
                            </td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                </div>

                {/* Sources list */}
                {currentOutput.sources && (
                  <div className="p-4 rounded-xl glass-panel">
                    <h4 className="text-xs font-semibold text-slate-400 uppercase tracking-wider mb-2 font-mono">
                      Citations & Source Verification Links:
                    </h4>
                    <div className="flex flex-wrap gap-2">
                      {currentOutput.sources.map((s, idx) => (
                        <a
                          key={idx}
                          href={s.url}
                          target="_blank"
                          rel="noreferrer"
                          className="inline-flex items-center gap-1.5 px-3 py-1 rounded-lg bg-white/5 hover:bg-white/10 border border-white/10 text-xs text-slate-300 hover:text-white transition-colors"
                        >
                          <span>{s.title}</span>
                          <ExternalLink className="w-3 h-3" />
                        </a>
                      ))}
                    </div>
                  </div>
                )}
              </div>
            )}

            {/* MVP Feature List */}
            {currentOutput.type === 'mvp_features' && currentOutput.data.mvpFeatures && (
              <div className="space-y-3">
                <div className="grid grid-cols-1 gap-3">
                  {currentOutput.data.mvpFeatures.map((feat) => {
                    const isP0 = feat.priority.includes('P0');
                    return (
                      <div
                        key={feat.id}
                        className={`p-4 rounded-xl border transition-all ${
                          isP0
                            ? 'border-white/20 bg-white/5'
                            : 'border-white/10 bg-white/[0.02]'
                        }`}
                      >
                        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 mb-2">
                          <h4 className="text-sm font-bold text-white flex items-center gap-2">
                            <span>{feat.title}</span>
                          </h4>
                          <div className="flex items-center gap-2">
                            <span
                              className={`text-[10px] font-mono font-medium px-2 py-0.5 rounded-md border ${
                                isP0
                                  ? 'bg-white/15 text-white border-white/25'
                                  : 'bg-white/5 text-slate-300 border-white/10'
                              }`}
                            >
                              {feat.priority}
                            </span>
                            <span className="text-[10px] font-mono px-2 py-0.5 rounded-md bg-white/5 border border-white/10 text-slate-400">
                              Complexity: {feat.complexity}
                            </span>
                          </div>
                        </div>

                        <p className="text-xs text-slate-300 leading-relaxed font-normal mb-2">
                          {feat.description}
                        </p>

                        <div className="text-[11px] text-slate-400 font-mono">
                          Target Stakeholder: <span className="text-slate-200">{feat.targetUserRole}</span>
                        </div>
                      </div>
                    );
                  })}
                </div>
              </div>
            )}

            {/* Unit Economics Chart */}
            {currentOutput.type === 'unit_economics' && currentOutput.data.unitEconomics && (
              <div className="space-y-6">
                <div className="grid grid-cols-1 sm:grid-cols-4 gap-3">
                  <div className="p-4 rounded-xl glass-panel">
                    <span className="text-[10px] font-mono uppercase text-slate-400 block">Month 12 MRR</span>
                    <span className="text-2xl font-bold text-white">
                      ${currentOutput.data.unitEconomics[11]?.mrr.toLocaleString()}
                    </span>
                  </div>
                  <div className="p-4 rounded-xl glass-panel">
                    <span className="text-[10px] font-mono uppercase text-slate-400 block">LTV : CAC Ratio</span>
                    <span className="text-2xl font-bold text-emerald-400">
                      32.0x
                    </span>
                  </div>
                  <div className="p-4 rounded-xl glass-panel">
                    <span className="text-[10px] font-mono uppercase text-slate-400 block">Target Blended CAC</span>
                    <span className="text-2xl font-bold text-slate-300">
                      ${currentOutput.data.unitEconomics[11]?.cac}
                    </span>
                  </div>
                  <div className="p-4 rounded-xl glass-panel">
                    <span className="text-[10px] font-mono uppercase text-slate-400 block">Est. Active Users</span>
                    <span className="text-2xl font-bold text-slate-200">
                      {currentOutput.data.unitEconomics[11]?.users.toLocaleString()}
                    </span>
                  </div>
                </div>

                {/* Recharts AreaChart: MRR Growth vs Burn Rate */}
                <div className="p-5 rounded-2xl glass-panel">
                  <h4 className="text-xs font-semibold uppercase tracking-wider text-slate-300 font-mono mb-4">
                    12-Month Projected MRR Trajectory ($) vs Net Burn
                  </h4>
                  <div className="h-72 w-full">
                    <ResponsiveContainer width="100%" height="100%">
                      <AreaChart data={currentOutput.data.unitEconomics}>
                        <defs>
                          <linearGradient id="colorMrr" x1="0" y1="0" x2="0" y2="1">
                            <stop offset="5%" stopColor="#ffffff" stopOpacity={0.3} />
                            <stop offset="95%" stopColor="#ffffff" stopOpacity={0} />
                          </linearGradient>
                          <linearGradient id="colorBurn" x1="0" y1="0" x2="0" y2="1">
                            <stop offset="5%" stopColor="#94a3b8" stopOpacity={0.2} />
                            <stop offset="95%" stopColor="#94a3b8" stopOpacity={0} />
                          </linearGradient>
                        </defs>
                        <CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.06)" />
                        <XAxis dataKey="month" stroke="#94a3b8" fontSize={11} />
                        <YAxis stroke="#94a3b8" fontSize={11} tickFormatter={(v) => `$${v / 1000}k`} />
                        <Tooltip
                          contentStyle={{
                            backgroundColor: '#121622',
                            borderColor: 'rgba(255,255,255,0.1)',
                            borderRadius: '8px',
                            fontSize: '12px',
                          }}
                        />
                        <Legend wrapperStyle={{ fontSize: '11px', paddingTop: '10px' }} />
                        <Area
                          type="monotone"
                          dataKey="mrr"
                          name="Monthly Recurring Revenue"
                          stroke="#ffffff"
                          strokeWidth={2}
                          fillOpacity={1}
                          fill="url(#colorMrr)"
                        />
                        <Area
                          type="monotone"
                          dataKey="burnRate"
                          name="Infrastructure & Ops Burn"
                          stroke="#94a3b8"
                          strokeWidth={1.5}
                          fillOpacity={1}
                          fill="url(#colorBurn)"
                        />
                      </AreaChart>
                    </ResponsiveContainer>
                  </div>
                </div>
              </div>
            )}

            {/* Tech Architecture Blueprint */}
            {currentOutput.type === 'tech_architecture' && currentOutput.data.techArchitecture && (
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {Object.entries(currentOutput.data.techArchitecture).map(([category, items]) => (
                  <div key={category} className="p-4 rounded-xl glass-panel">
                    <h4 className="text-xs font-semibold uppercase tracking-wider text-slate-300 font-mono mb-2.5">
                      {category.replace(/([A-Z])/g, ' $1')}
                    </h4>
                    <div className="space-y-1.5">
                      {(items as string[]).map((item: string, idx: number) => (
                        <div
                          key={idx}
                          className="flex items-center gap-2 text-xs text-slate-200 bg-white/[0.03] p-2 rounded-lg border border-white/5"
                        >
                          <Cpu className="w-3.5 h-3.5 text-slate-400" />
                          <span>{item}</span>
                        </div>
                      ))}
                    </div>
                  </div>
                ))}
              </div>
            )}

            {/* Launch Plan Roadmap */}
            {currentOutput.type === 'launch_plan' && currentOutput.data.launchPlan && (
              <div className="rounded-2xl border border-white/10 overflow-hidden bg-white/[0.01]">
                <div className="overflow-x-auto">
                  <table className="w-full text-left text-xs">
                    <thead className="bg-[#121622] text-slate-400 uppercase text-[10px] font-mono border-b border-white/10">
                      <tr>
                        <th className="p-3.5">Timeline</th>
                        <th className="p-3.5">Milestone Phase</th>
                        <th className="p-3.5">Execution Action</th>
                        <th className="p-3.5">Acquisition Channel</th>
                        <th className="p-3.5">Lead Agent</th>
                        <th className="p-3.5 text-white">Success Metric</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-white/5 text-slate-300">
                      {currentOutput.data.launchPlan.map((m, idx) => (
                        <tr key={idx} className="hover:bg-white/[0.02] transition-colors">
                          <td className="p-3.5 font-mono text-white whitespace-nowrap font-bold">
                            {m.day}
                          </td>
                          <td className="p-3.5 font-semibold text-white whitespace-nowrap">
                            {m.phase}
                          </td>
                          <td className="p-3.5 leading-relaxed max-w-[240px]">
                            {m.action}
                          </td>
                          <td className="p-3.5 whitespace-nowrap text-slate-400 font-mono text-[11px]">
                            {m.channel}
                          </td>
                          <td className="p-3.5 whitespace-nowrap text-slate-300 font-medium">
                            {m.owner}
                          </td>
                          <td className="p-3.5 whitespace-nowrap font-medium text-emerald-400">
                            {m.metric}
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>
            )}

            {/* Custom Report fallback */}
            {currentOutput.type === 'custom_report' && currentOutput.data.customContent && (
              <div className="p-6 rounded-2xl glass-panel space-y-4">
                <h3 className="text-base font-bold text-white">
                  {currentOutput.data.customContent.heading}
                </h3>
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                  {currentOutput.data.customContent.items.map((item: { label: string; value: string }, idx: number) => (
                    <div key={idx} className="p-3 rounded-xl bg-white/[0.03] border border-white/5">
                      <span className="text-[10px] font-mono uppercase text-slate-400 block mb-1">
                        {item.label}
                      </span>
                      <span className="text-xs font-semibold text-white">{item.value}</span>
                    </div>
                  ))}
                </div>
                <p className="text-xs text-slate-300 leading-relaxed bg-black/20 p-4 rounded-xl border border-white/5">
                  {currentOutput.data.customContent.prose}
                </p>
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
};
